name: Deployment for the dev testing

on:
  push:
    branches:
      - dev-test

jobs:
  deploy:
    name: deploy app to netlify
    runs-on: ubuntu-latest
    env:
      ENV: TESTING

    steps:
      #code checkout
      - name: Checkout
        uses: actions/checkout@v4

        #setup node js
      - name: setup node js environment
        uses: actions/setup-node@v4

        #install netlify-cli
      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g
        #install dependences
      - name: install dependencies
        run:
          npm install

          # build the react app
      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir dist \
            --auth ${{ secrets.MY_TOKEN_SECRET }}
  # cache the dependencies to speed up build
